### PR TITLE
ngrok: update readme to clarify example

### PR DESCRIPTION
**Pull request by jrobsonchase**

### CODE REVIEW

**Comment by jrobsonchase** [comment]
Current dependencies on/for this PR:
* main
  * **PR #77** <a href="https://app.graphite.dev/github/pr/ngrok/ngrok-rs/77" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/ngrok/ngrok-rs/77?utm_source=stack-comment).

**Review by bobzilladev — APPROVED** [review]
The changes lgtm. Is there a standard-ish way to update versions in readme's automatically that we could move to?

**Comment by jrobsonchase** [comment]
I wish :confused: 

The crates badge has the benefit of fetching from another service that keeps track of the latest on crates.io. We could maybe do an iframe to a file in the repo, but that feels kinda gross and might not translate well to rustdocs or the crates.io readme. The only other alternative would be templating/generating it, but that's not great either.

**Comment by bobzilladev** [comment]
Spose we probably want it copy-pasteable, so yeah an iframe loading some text in or something awful. Googling around only finding folks using github actions to edit the file and commit a new version by hand. Did find this thing which might make it less tedious: https://github.com/MathieuSoysal/file-updater-for-release

**Pull request merged**
